# Generated by Django 2.2.3 on 2019-07-28 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nice', '0002_auto_20190728_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='korean',
            name='interest',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='korean',
            name='nation',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='korean',
            name='region',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='korean',
            name='sex',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='korean',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lforeigner',
            name='interest',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='lforeigner',
            name='nation',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='lforeigner',
            name='region',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='lforeigner',
            name='sex',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='lforeigner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sforeigner',
            name='interest',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='sforeigner',
            name='nation',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='sforeigner',
            name='region',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='sforeigner',
            name='sex',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='sforeigner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='K_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcontents', models.TextField()),
                ('korean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kcomment', to='nice.Korean')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
