# Generated by Django 2.2.3 on 2019-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0003_auto_20190729_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korean',
            name='interest',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='korean',
            name='nation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='korean',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='korean',
            name='sex',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lforeigner',
            name='interest',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lforeigner',
            name='nation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lforeigner',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lforeigner',
            name='sex',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sforeigner',
            name='interest',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sforeigner',
            name='nation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sforeigner',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sforeigner',
            name='sex',
            field=models.CharField(max_length=50),
        ),
    ]
