# Generated by Django 2.2.3 on 2019-07-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0004_auto_20190729_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lf_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfcontents', models.TextField()),
                ('lforeigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lfcomment', to='nice.Korean')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
