# Generated by Django 2.2.3 on 2019-07-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0005_lf_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sf_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfcontents', models.TextField()),
                ('sforeigner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sfcomment', to='nice.Korean')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
